### ISSUE TITLE
[Roadmap] Checklist refactor Javascript Course

### ISSUE THREAD

**Issue by harrytran998** [techmely/hoc-lap-trinh#112]
Relate to #107 

Hiện tại đây là cấu trúc của khoá học JS, một trong những khoá quan trọng nhất của 1 Frontend Developer nói chung!
Nên làm cẩn thận nó từng ly, từng tý một cho thật nuột. 

![image](https://github.com/techmely/hoc-lap-trinh/assets/24296018/550e7b62-f2f1-45d3-8ca0-9da84e4f8716)

![image](https://github.com/techmely/hoc-lap-trinh/assets/24296018/ca452c7a-1409-4456-9403-edb9f466134d)
[Chart đánh giá engagement time với words](https://blog.chartbeat.com/2022/07/07/optimal-article-length-for-engagement/)

Ở chi tiết mỗi bài viết, sẽ nên căn cứ vào độ quan trọng của bài viết + số lượng bài viết + pageviews + engament times để đánh giá độ hiệu quả của nó!

# DOD

- [ ] Thêm 10 main points - What you'll learn - ở sau phần description khoá học
- [ ] Thêm CTA đăng ký Premium User gói **GOALs**
- [ ] Đổi font chữ quốc dân cho content dễ đọc - Font hiện tại ở đọc khó vl với những người mắt kém
- [ ] Thêm phần `Premium Quiz` cho các phần học JS -- cc @thaycacac có gì thảo luận phần này để tạo vốn cho team
- [ ] 1.1. Lời giới thiệu #116 
		![image](https://github.com/techmely/hoc-lap-trinh/assets/24296018/5c354808-d272-4fc3-b4d2-985836debe04)
	- Từ `engament time` trung bình ~= 26s với 1762 từ --> Bài viết chưa đạt, cần ít nhất trên 50s mới coi là ok --> ✅ NEED REFACTOR
- [ ] 1.2. Setup phần mềm để có thể tương tác với Javascript code - Text Editor/IDE/Emacs
- [ ] 1.3. Bỏ đi phần Devtools là gì... --> Mới học chưa cần thiết phải biết cái này
- [ ] 2.1 Chương trình JS đầu tiên
		Bài này Engagement time tốt, nhưng khi đọc qua vẫn thấy chưa đủ hay + ví dụ dễ hiểu
		![image](https://github.com/techmely/hoc-lap-trinh/assets/24296018/bd847717-aae6-4b8d-acd2-2c8f4c0e3ffd)
		- [ ] Thêm ảnh ví dụ dễ hiểu phần Browser console. 
		- [ ] Hướng dẫn tạo và chạy `Chương trình JavaScript đầu tiên với HTML` trên StackBlit cho dễ hiểu và dễ sử dụng(nhúng vào website được) + Có thể tracking được thêm họ có tương tác trực tiếp với nó hay không
- [ ] 2.2 Title chưa hợp lý ~~Cấu trúc code trong Javascript~~ --> Một số điều cơ bản trong javascript bạn cần biết.
		Bài này nội dung nó chả liên quan gì tới title, nên tạm thời viết chung chung.
		- [ ] Sửa title
		- [ ] Update phần content thành Interactive content
- [ ] 2.3 

.... Continue Update...

## Câu hỏi cần thảo luận 

- [ ] Nên có các phần code Interactive cho người đọc dễ hình dung + tự mò nghịch được + thêm tracking! Cụ thể là embed iframe của https://stackblitz.com vào các page bài học
